# syntax=docker/dockerfile:1
# Pour le lancer, taper la commande: docker compose -f docker-compose-gitk.yaml up --build
name: gitk
services:
  gitk:
    build:
      dockerfile: ../Dockerfiles/Dockerfile_gitk
      args:
        apt_proxy: $apt_proxy
    network_mode: host
    environment:
      - DISPLAY
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority:rw
    image: gitk
