# syntax=docker/dockerfile:1
name: gitk
services:
    build:
      dockerfile: Dockerfile_gitk
      args:
        apt_proxy: $apt_proxy
    gitk:
        network_mode: host
        environment:
            - DISPLAY
        volumes:
            - $HOME/.Xauthority:/root/.Xauthority:rw
        image: gitk
